# -*- coding: utf-8 -*-
"""Pyspark Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMCt6M_IdIJxyeoyLyYb0YrzxR0D4Hxy
"""

#Installing pyspark
!pip install pyspark

#Load the CSV File
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#Importing the necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from pyspark.sql import SparkSession
from pyspark.sql.functions import col,year,month
# %matplotlib inline

#Initialize Spark Session
spark = SparkSession.builder.appName("Pyspark Analysis").getOrCreate()

#load csv file into pyspark dataframe
sales = spark.read.csv('/content/drive/My Drive/SalesOrderDetail.csv', header=True, inferSchema=True)

#Create temporary view for SQL Queries
sales.createOrReplaceTempView("sales_order")

#View the data
sales.show(5)

#view the schema
sales.printSchema()

sales.describe()

sales.summary().show()

#Querying the dataset
data= spark.sql("""
SELECT *
FROM sales_order
""")

#Calculate total sales per product
total_sales= data.groupBy("ProductID").sum("OrderQty").withColumnRenamed("sum(OrderQty)","TotalSales")

#Calculate the monthly sales trend
monthly_sales_trend = data.withColumn("Year", year("ModifiedDate")).withColumn("Month", month("ModifiedDate"))

monthly_sales_trend= monthly_sales_trend.groupBy("ProductID", "Year","Month").sum("OrderQty").withColumnRenamed("sum(OrderQty)", "MonthlySales").show()

#Identify top 10 Cutomers
top_customers=data.groupBy("SalesOrderDetailID").sum("OrderQty").withColumnRenamed("sum(OrderQty)",
"Total_Sales").orderBy(col("Total_Sales").desc()).limit(10).show()

#Year over Year growth

year= data.withColumn("Year", year("ModifiedDate"))

year= year.groupBy("Year").sum("LineTotal").withColumnRenamed("sum(LineTotal)", "Year_over_Year").orderBy(col("Year_over_Year").desc()).show()

total_sales.createOrReplaceTempView("total_sales")

result_df = spark.sql("""
 SELECT ProductID, TotalSales
 FROM total_sales
 ORDER BY TotalSales DESC
 """).show()

#Convert pyspark Dataframe to Pandas Dataframe
monthly_sales_trend = monthly_sales_trend.toPandas()

#Plotting Monthly sales trend
plt.figure(figsize=(10,6))
for productid in monthly_sales_trend['ProductID'].unique():
  product_data = monthly_sales_trend[monthly_sales_trend['ProductID']==productid]
  plt.plot(product_data['Month'], product_data['MonthlySales'], label=f'Product {productid}')

  plt.xlabel('Month')
  plt.ylabel('Monthly Sales')
  plt.title('Monthly Sales Trends by Product')
  plt.legend()
  plt.show()